version: '3.1'
services:

  postgres:
    container_name: pg-container
    image: postgres
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer-container
    image: adminer
    restart: always
    ports:
      - 8181:8080
    depends_on:
      - 'postgres'
      
  web:
    container_name: fest-container
    entrypoint: ["/bin/ash", "./entrypoint.sh"]
    build:
      context: .
      dockerfile: Dockerfile
    image: 'fest'
    ports:
      - 3000:3000
    depends_on:
      - 'postgres'